language: php

sudo: false

php:
  - '5.6'
  - '7.0'

before_install:
 - composer install

script:
 - sh run_tests.sh

after_success:
 - php vendor/bin/coveralls -v

notifications:
  email:
    - caio.f.r.amd@gmail.com
